version: '3.8'
services:
  dev-mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: pista
      MYSQL_PASSWORD: password
    restart: always
    networks:
      - dev-network

networks:
  dev-network:
